/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoteNoteIdRouteImport } from './routes/note.$noteId'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as ApiPortalRouteImport } from './routes/api/portal'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as ApiWebhooksPolarRouteImport } from './routes/api/webhooks/polar'
import { Route as ApiWebhooksClerkRouteImport } from './routes/api/webhooks/clerk'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteNoteIdRoute = NoteNoteIdRouteImport.update({
  id: '/note/$noteId',
  path: '/note/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalRoute = ApiPortalRouteImport.update({
  id: '/api/portal',
  path: '/api/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksPolarRoute = ApiWebhooksPolarRouteImport.update({
  id: '/api/webhooks/polar',
  path: '/api/webhooks/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksClerkRoute = ApiWebhooksClerkRouteImport.update({
  id: '/api/webhooks/clerk',
  path: '/api/webhooks/clerk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/notes': typeof NotesRoute
  '/profile': typeof ProfileRoute
  '/success': typeof SuccessRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/portal': typeof ApiPortalRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/note/$noteId': typeof NoteNoteIdRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/notes': typeof NotesRoute
  '/profile': typeof ProfileRoute
  '/success': typeof SuccessRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/portal': typeof ApiPortalRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/note/$noteId': typeof NoteNoteIdRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/notes': typeof NotesRoute
  '/profile': typeof ProfileRoute
  '/success': typeof SuccessRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/portal': typeof ApiPortalRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/note/$noteId': typeof NoteNoteIdRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/notes'
    | '/profile'
    | '/success'
    | '/terms-and-conditions'
    | '/api/checkout'
    | '/api/portal'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/note/$noteId'
    | '/api/webhooks/clerk'
    | '/api/webhooks/polar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/notes'
    | '/profile'
    | '/success'
    | '/terms-and-conditions'
    | '/api/checkout'
    | '/api/portal'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/note/$noteId'
    | '/api/webhooks/clerk'
    | '/api/webhooks/polar'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/notes'
    | '/profile'
    | '/success'
    | '/terms-and-conditions'
    | '/api/checkout'
    | '/api/portal'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/note/$noteId'
    | '/api/webhooks/clerk'
    | '/api/webhooks/polar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  NotesRoute: typeof NotesRoute
  ProfileRoute: typeof ProfileRoute
  SuccessRoute: typeof SuccessRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiPortalRoute: typeof ApiPortalRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  NoteNoteIdRoute: typeof NoteNoteIdRoute
  ApiWebhooksClerkRoute: typeof ApiWebhooksClerkRoute
  ApiWebhooksPolarRoute: typeof ApiWebhooksPolarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/$noteId': {
      id: '/note/$noteId'
      path: '/note/$noteId'
      fullPath: '/note/$noteId'
      preLoaderRoute: typeof NoteNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal': {
      id: '/api/portal'
      path: '/api/portal'
      fullPath: '/api/portal'
      preLoaderRoute: typeof ApiPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/polar': {
      id: '/api/webhooks/polar'
      path: '/api/webhooks/polar'
      fullPath: '/api/webhooks/polar'
      preLoaderRoute: typeof ApiWebhooksPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/clerk': {
      id: '/api/webhooks/clerk'
      path: '/api/webhooks/clerk'
      fullPath: '/api/webhooks/clerk'
      preLoaderRoute: typeof ApiWebhooksClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  NotesRoute: NotesRoute,
  ProfileRoute: ProfileRoute,
  SuccessRoute: SuccessRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiPortalRoute: ApiPortalRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  NoteNoteIdRoute: NoteNoteIdRoute,
  ApiWebhooksClerkRoute: ApiWebhooksClerkRoute,
  ApiWebhooksPolarRoute: ApiWebhooksPolarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
